import React, { useState } from 'react'

const Testimonials = () => {

    const [currentIndex, setCurrentIndex]  = useState(0);
    const testimonials = [ // test case generated by gemini
    {
        quote: "This is the best product I've ever used. It significantly improved my workflow!",
        author: "Ahmad Hamid",
        id: 0
    },
    {
        quote: "Incredible service! The team went above and beyond to help me out.",
        author: "Fatima Al-Marri",
        id:1
    },
    {
        quote: "Highly recommended. Simple, intuitive, and extremely effective.",
        author: "Khalid Mansour",
        id: 2
    },
    {
        quote: "I was skeptical at first, but this truly exceeded all my expectations. A game-changer!",
        author: "Sara Abdullah",
        id: 3
    },
    {
        quote: "Absolutely fantastic! Saved me so much time and effort. Couldn't be happier.",
        author: "Yousef Ibrahim",
        id: 4
    }
];

const incrementIndex = () => {
    if(currentIndex<(testimonials.length-1)){
        setCurrentIndex(currentIndex => currentIndex+1)
    }
}
const decrementIndex = () => {
    if (currentIndex>0){
        setCurrentIndex(currentIndex => currentIndex-1)
    }
}


  return (
    <div className='testimonials'>
        <div key={testimonials[currentIndex].id}>
        <p  className='quote'>
            {testimonials[currentIndex].quote}</p>
        <p  className='author'>- {testimonials[currentIndex].author}</p>
    </div>
    <div className='previous-next'>
        <button onClick={decrementIndex}>previus</button>
        <button onClick={incrementIndex}>next</button>
    </div>
    </div>

  )
}

export default Testimonials